name: "Upstream Sync"

on:
  schedule:
    - cron: "0 */1 * * *"

  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    permissions:
      contents: write

    steps:
      # REQUIRED step
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout target repo and merge
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge upstream changes
        run: |
          git remote add upstream https://github.com/OpenListTeam/OpenList.git
          git fetch upstream
          git merge --no-edit upstream/main
          git push
